---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/definitions":
    get:
      summary: list definitions
      responses:
        '200':
          description: successful
    post:
      summary: create definition
      responses:
        '200':
          description: successful
  "/api/definitions/{id}":
    parameters:
    - name: id
      in: path
      description: id
      required: true
      schema:
        type: string
    get:
      summary: show definition
      responses:
        '200':
          description: successful
    patch:
      summary: update definition
      responses:
        '200':
          description: successful
    put:
      summary: update definition
      responses:
        '200':
          description: successful
    delete:
      summary: delete definition
      responses:
        '200':
          description: successful
